---
openapi: 3.0.1
info:
  title: Furo
  description: Earn, stream and automate your DAO salaries and token vesting with Furo.
  version: "2.0.0"
servers:
- url: https://sushi.com
- url: http://www.sushi.com
paths:
  /furo/api/user/{chainId}/{address}/streams:
    get:
      summary: Get user streams
      description: Get user streams
      parameters:
      - name: chainId
        in: path
        description: Chain ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: address
        in: path
        description: User address
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              examples:
                UserStreams:
                  value:
                    incomingStreams:
                    - id: "1018"
                      __typename: Stream
                      status: ACTIVE
                      startedAt: "1655276100"
                      expiresAt: "1676447340"
                      modifiedAtTimestamp: "1655275790"
                      extendedAtTimestamp: "0"
                      initialShares: "190562207738"
                      initialAmount: "191999999999"
                      extendedShares: "0"
                      remainingShares: "164797739465"
                      withdrawnAmount: "25981721647"
                      recipient:
                        id: 0x23defc2ca207e7fbd84ae43b00048fb5cb4db5b2
                      createdBy:
                        id: 0xc39c2d6eb8adef85f9caa141ec95e7c0b34d8dec
                      token:
                        id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                        symbol: SUSHI
                        name: SushiToken
                        decimals: "18"
                    outgoingStreams:
                    - id: "1014"
                      __typename: Stream
                      status: ACTIVE
                      startedAt: "1654534260"
                      expiresAt: "1654620300"
                      modifiedAtTimestamp: "1654533995"
                      extendedAtTimestamp: "0"
                      initialShares: "90000000000"
                      initialAmount: "91999999999"
                      extendedShares: "0"
                      remainingShares: "70000000000"
                      withdrawnAmount: "22000000000"
                      recipient:
                        id: 0xc39c2d6eb8adef85f9caa141ec95e7c0b34d8dec
                      createdBy:
                        id: 0x23defc2ca207e7fbd84ae43b00048fb5cb4db5b2
                      token:
                        id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                        symbol: SUSHI
                        name: SushiToken
                        decimals: "18"
      servers:
      - url: http://www.sushi.com
    servers:
    - url: http://www.sushi.com
  /furo/api/stream/{chainId}/{streamId}:
    get:
      summary: Get stream 
      description: Stream status can be `ACTIVE` or `CANCELLED`
      parameters:
      - name: chainId
        in: path
        description: Chain ID number
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: streamId
        in: path
        description: Stream ID number, starts at 1000
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              examples:
                Stream:
                  value:
                    id: "1021"
                    __typename: Stream
                    status: ACTIVE
                    startedAt: "1654896300"
                    expiresAt: "1685269219"
                    extendedAtTimestamp: "0"
                    initialShares: "190562207738"
                    initialAmount: "191999999999"
                    extendedShares: "0"
                    remainingShares: "164797739465"
                    withdrawnAmount: "25981721647"
                    txHash: 0x8ef330231938de480733823ce27f717ee80149b81d0ea26e66b19578c100e503
                    recipient:
                      id: 0xc86498822ef633f6e1e971484c56e3a087ecc333
                    createdBy:
                      id: 0x19b3eb3af5d93b77a5619b047de0eed7115a19e7
                    token:
                      id: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
                      symbol: USDC
                      name: USD Coin
                      decimals: "6"
      servers:
      - url: https://sushi.com
    servers:
    - url: https://sushi.com
  /furo/api/stream/{chainId}/{streamId}/transactions:
    get:
      summary: Get stream transactions
      description: > 
        Get stream transactions
        
        
        Transactions types:
        
        
        - `DEPOSIT`  
        
        
        - `WITHDRAWAL`  
        
        
        - `EXTEND` - A stream can be topped up, increasing the amount
        
        - `DISBURSEMENT` - When a stream is cancelled, two disbursement transactions
        will be created, returning the remaining shares to the recipient and the creator.
      parameters:
      - name: chainId
        in: path
        description: Chain ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: streamId
        in: path
        description: Stream ID number, starts at 1000
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              examples:
                StreamTransactions:
                  value:
                  - id: 1021:tx:1
                    type: WITHDRAWAL
                    amount: "397004598"
                    toBentoBox: false
                    createdAtBlock: "14985857"
                    createdAtTimestamp: "1655568392"
                    txHash: 0x1f914b83ff4eeed923b89cfda57220742d3a52e592bf8f011275804d0e0599e3
                    token:
                      id: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
                      name: USD Coin
                      symbol: USDC
                      decimals: "6"
                    to:
                      id: 0xc86498822ef633f6e1e971484c56e3a087ecc333
                  - id: 1021:tx:0
                    type: DEPOSIT
                    amount: "190562207738"
                    toBentoBox: false
                    createdAtBlock: "14940306"
                    createdAtTimestamp: "1654891693"
                    txHash: 0x8ef330231938de480733823ce27f717ee80149b81d0ea26e66b19578c100e503
                    token:
                      id: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
                      name: USD Coin
                      symbol: USDC
                      decimals: "6"
                    to:
                      id: 0xc86498822ef633f6e1e971484c56e3a087ecc333
      servers:
      - url: http://www.sushi.com
    servers:
    - url: http://www.sushi.com
  /furo/api/user/{chainId}/{address}/vestings:
    get:
      summary: Get user vests
      description: Get user vests
      parameters:
      - name: chainId
        in: path
        description: Chain ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: address
        in: path
        description: User address
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              examples:
                Vests:
                  value:
                    incomingVestings:
                    - id: "2"
                      __typename: Vesting
                      status: ACTIVE
                      steps: "1"
                      startedAt: "1654139700"
                      expiresAt: "1656040320"
                      modifiedAtTimestamp: "1654139575"
                      cliffDuration: "1295820"
                      stepDuration: "604800"
                      stepAmount: "99999999999999"
                      cliffAmount: "1000000000000001"
                      totalAmount: "1100000000000000"
                      withdrawnAmount: "0"
                      fromBentoBox: false
                      token:
                        id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                        symbol: SUSHI
                        name: SushiToken
                        decimals: "18"
                      recipient:
                        id: 0x7a5f66eb194f629db12f25bd0695819cb690fcc7
                      createdBy:
                        id: 0x7a5f66eb194f629db12f25bd0695819cb690fcc7
                    - id: "3"
                      __typename: Vesting
                      status: CANCELLED
                      steps: "9"
                      startedAt: "1654152000"
                      expiresAt: "1659595260"
                      modifiedAtTimestamp: "1654782844"
                      cliffDuration: "60"
                      stepDuration: "604800"
                      stepShares: "1969395743041858967011"
                      cliffShares: "23632786728961078424936"
                      initialShares: "94531033478468001237332"
                      initialAmount: "99999880000000000000000"
                      remainingShares: "94531033478468001237332"
                      withdrawnAmount: "0"
                      fromBentoBox: false
                      token:
                        id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                        symbol: SUSHI
                        name: SushiToken
                        decimals: "18"
                      recipient:
                        id: 0x7a5f66eb194f629db12f25bd0695819cb690fcc7
                      createdBy:
                        id: 0x7a5f66eb194f629db12f25bd0695819cb690fcc7
                    outgoingVestings:
                    - id: "2"
                      __typename: Vesting
                      status: ACTIVE
                      steps: "1"
                      startedAt: "1654139700"
                      expiresAt: "1656040320"
                      modifiedAtTimestamp: "1654139575"
                      cliffDuration: "1295820"
                      stepDuration: "604800"
                      stepShares: "99999999999999"
                      cliffShares: "1000000000000001"
                      initialShares: "1000000000000000"
                      initialAmount: "1100000000000000"
                      remainingShares: "1000000000000000"
                      withdrawnAmount: "0"
                      fromBentoBox: false
                      token:
                        id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                        symbol: SUSHI
                        name: SushiToken
                        decimals: "18"
                      recipient:
                        id: 0x7a5f66eb194f629db12f25bd0695819cb690fcc7
                      createdBy:
                        id: 0x7a5f66eb194f629db12f25bd0695819cb690fcc7
      servers:
      - url: http://www.sushi.com
    servers:
    - url: http://www.sushi.com
  /furo/api/vesting/{chainId}/{vestId}:
    get:
      summary: Get vest 
      description: >
        Get vest 
        
        
        Vest status can be `ACTIVE` or `CANCELLED`
      parameters:
      - name: chainId
        in: path
        description: Chain ID number
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: vestId
        in: path
        description: Vest ID number, starts at 1
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              examples:
                Vest:
                  value:
                    id: "1"
                    __typename: Vesting
                    status: ACTIVE
                    steps: "4"
                    startedAt: "1655222400"
                    expiresAt: "1702486800"
                    modifiedAtTimestamp: "1654012508"
                    cliffDuration: "15814800"
                    stepDuration: "7862400"
                    stepShares: "34530387"
                    cliffShares: "0"
                    initialShares: "120000000"
                    initialAmount: "138121548"
                    withdrawnAmount: "0"
                    fromBentoBox: false
                    txHash: 0x269479de4d7f84f0fc398ee545d75353cd8c24ffdb364336bb2df9c15a2c1d33
                    token:
                      id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                      symbol: SUSHI
                      name: SushiToken
                      decimals: "18"
                    recipient:
                      id: 0xd4bad6e7887110081aa8ee9e16c9341890cae7e5
                    createdBy:
                      id: 0xc9ecab4ae699ac237a5abc5a7f2c08afc09aa253
      servers:
      - url: http://www.sushi.com
    servers:
    - url: http://www.sushi.com
  /furo/api/vesting/{chainId}/{vestId}/transactions:
    get:
      summary: Get vest transactions
      description:  > 
        Get vest transactions
        
        
        Transactions types:
        
        
        - `DEPOSIT`  
        
        
        - `WITHDRAWAL`  
        
        
        - `DISBURSEMENT` - When a vest is cancelled, two disbursement transactions
        will be created, returning the remaining shares to the recipient and the creator.
      parameters:
      - name: chainId
        in: path
        description: Chain ID number
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: vestId
        in: path
        description: Vest ID number, starts at 1
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              examples:
                VestTransactions:
                  value:
                  - id: 1:tx:0
                    type: DEPOSIT
                    amount: "138121548"
                    toBentoBox: true
                    createdAtBlock: "14879604"
                    createdAtTimestamp: "1654012508"
                    txHash: 0x269479de4d7f84f0fc398ee545d75353cd8c24ffdb364336bb2df9c15a2c1d33
                    token:
                      id: 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2
                      symbol: SUSHI
                      name: SushiToken
                      decimals: "18"
                    to:
                      id: 0xd4bad6e7887110081aa8ee9e16c9341890cae7e5
      servers:
      - url: http://www.sushi.com
    servers:
    - url: http://www.sushi.com
components: {}